name: activerecord-firewall

type: ruby

up:
  - ruby: 2.6.6
  - bundler

commands:
  console:
    desc:   'start a console'
    run:    test/dummy/bin/rails console
  run:
    desc:   'start the application'
    run:    test/dummy/bin/rails server
  test:
    syntax:
      argument: file
      optional: args...
    run: bin/testunit
